# Generated by Django 3.2 on 2021-04-26 14:18

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RideDriver',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('location_start', models.CharField(max_length=100)),
                ('location_end', models.CharField(max_length=100)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('point', models.FloatField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('time_create', models.TimeField(blank=True, null=True)),
                ('time_pickup', models.TimeField(blank=True, null=True)),
                ('recommended_price', models.FloatField(blank=True, null=True)),
                ('point', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('location_pickup', models.CharField(max_length=100)),
                ('location_to', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ridedriver')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.riderequest')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthday', models.DateField(blank=True)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('profile_image', models.ImageField(upload_to=core.models.upload_to_student_profile)),
                ('idcard_image', models.ImageField(upload_to=core.models.upload_to_student_idcard)),
                ('status', models.IntegerField(choices=[(1, 'Enable'), (0, 'Disable')], default=1)),
                ('is_driver', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('uni_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('uni_name', models.CharField(max_length=100)),
                ('uni_city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=30)),
                ('vehicle_manufacturer', models.CharField(max_length=20)),
                ('cylinder_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentVehicle',
            fields=[
                ('svehicle_id', models.AutoField(primary_key=True, serialize=False)),
                ('color', models.CharField(max_length=10)),
                ('lp_number', models.CharField(max_length=20)),
                ('lp_image', models.ImageField(upload_to=core.models.upload_to_vehicle_license_plate)),
                ('ve_image', models.ImageField(upload_to=core.models.upload_to_vehicle_image)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.university'),
        ),
        migrations.CreateModel(
            name='ScheduleCancel',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('location_pickup', models.CharField(max_length=100)),
                ('location_end', models.CharField(max_length=100)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('lenght', models.FloatField()),
                ('duration', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.schedule')),
            ],
        ),
        migrations.AddField(
            model_name='riderequest',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.student'),
        ),
        migrations.AddField(
            model_name='ridedriver',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.student'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.route')),
            ],
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('campus_id', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('campus_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.university')),
            ],
        ),
    ]
